PI-230 Create incident report page and form (UI only)
rfcx/rfcx-org pull request #20
Opened 2020-12-22 08:37 UTC by utainwitedsonthi

2020-12-23 10:20 UTC, rassokhin-s requested changes
In addition to comments which I left for the code:
1) The UI design looks not very clear for the first view. Labels column on the left side looks liked a page sidebar. Please make it look more like a form.
2) We have a contact form on the homepage. I think they should have similar design. So either we make this form look similar, or we change the homepage form to have new design.
3) `select` and `input` elements have different border colors.

2020-12-23 10:20 UTC, rassokhin-s commented on src/html/modules/report/about.html
> +<div class="container">
1) `src/html/modules/report/about.html` is not correct name for the file's purpose. It contains the form, so I would name it `form.html`
2) If you take a look at other pages and files, you will see that we use more precise word for naming the root class in the file (not `container`)

2020-12-23 10:20 UTC, rassokhin-s commented on src/html/modules/report/about.html
> +        <textarea id="comments" name="comments" style="height:200px"></textarea>
Please avoid using inline styles in this repo. Each html file has its own styles file where you can put all your styles code.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +    float: left;
Once you read about BEM methodology for styles, you will find out that you can do the following:
```
.form {
  &__column {
    float: left;
    margin-top: 10px;
    &_20 {
      width: 20%;
    }
    &_40 {
      width: 40%;
    }
  }
}
```

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +label {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +textarea {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +input[type=date] {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +input[type=time] {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +input[type=url] {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +input[type=submit] {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +input[type=submit]:hover {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +textarea {
Don't apply styles to tag unless you are sure that it won't affect other components on the page.
Please make it with classname instead.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +  .container_column_75 {
You can write it shorter with BEM methodology and Less.

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +  font-size: large;
This one will look different for different users...

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +  margin-top: 20px;
These two lines can be replaced with one:
```
margin: 20px auto 0;
```

2020-12-23 10:20 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +  &_row::after {
We already have `clearfix` mixing in this repo. Please use it.

2021-01-12 08:59 UTC, rassokhin-s commented on src/less/modules/report/form.less
> +      margin-top: 10px;
You don't need to repeat `float: left; margin-top: 10px;` for every of `&_20`, `&_25`, `&_40`, `&_75`. You can put it one time in the following place:
```
&__column {
  float: left;
  margin-top: 10px;
```

2021-01-12 08:59 UTC, rassokhin-s commented on src/less/modules/report/report.less
> +  font-size: large;
This is not fixed yet.

2021-01-12 09:00 UTC, rassokhin-s requested changes
There is still two small change requests.

2021-01-12 09:05 UTC, rassokhin-s commented
https://user-images.githubusercontent.com/2122991/104292585-10654300-54ce-11eb-98b9-cd91e56bf280.mov
A few other comments:
1) I'm not able to open calendar, date and time pickers by clicking on them - only by clicking on the icon. It should open when I click on any place of the input.
2) When hover over dropdown, calender, date or time picker, the cursor should be "pointer".
3) When I open calendar or date or time picker it uses blue color as highlight. We don't have this color in our branding. Please use green instead.

2021-02-01 05:57 UTC, antonyharfield commented
We will not merge this and instead make it part of the new incident response dashboard.

2021-02-01 05:57 UTC, closed without merging